/*CREATE SCHEMA RENTACAR;

CREATE TABLE RENTACAR.CLIENTE (
	NIF				INT				NOT NULL,
	Endereco		VARCHAR(30),
	Num_carta		INT				NOT NULL,
	Nome			VARCHAR(30)		NOT NULL,
	PRIMARY KEY (NIF));*/

CREATE TABLE RENTACAR.BALCAO (
	NUM				INT				NOT NULL,
	Endereco		VARCHAR(30),
	Nome			VARCHAR(30)		NOT NULL,
	PRIMARY KEY (NUM));

CREATE TABLE RENTACAR.TPVEICULO (
	Codigo				INT				NOT NULL,
	Designacao			VARCHAR(30),
	ArCondicionado		BINARY(1)		NOT NULL,
	PRIMARY KEY (Codigo));

CREATE TABLE RENTACAR.LIGEIRO(
	NumLugares		INT			NOT NULL,
	Portas			TINYINT,
	Combustivel		BINARY(1),
	Codigo			INT			NOT NULL,
	PRIMARY KEY(Codigo),
	FOREIGN KEY (Codigo) REFERENCES RENTACAR.TPVEICULO(Codigo));

CREATE TABLE RENTACAR.PESADO(
	Passageiro		INT			NOT NULL,
	Peso			INT,
	Codigo			INT			NOT NULL,
	PRIMARY KEY(Codigo),
	FOREIGN KEY (Codigo) REFERENCES RENTACAR.TPVEICULO(Codigo));


CREATE TABLE RENTACAR.VEICULO(
	Matricula		VARCHAR(6)		NOT NULL,
	Marca			VARCHAR(15)		NOT NULL,
	Ano				INT				NOT NULL,
	FK_TpVeiculo	INT				NOT NULL,
	PRIMARY KEY(Matricula),
	FOREIGN KEY (FK_TpVeiculo) REFERENCES RENTACAR.TPVEICULO(Codigo));

CREATE TABLE RENTACAR.ALUGUER (
	Numero			INT				NOT NULL,
	Duracao			TIME			NOT NULL,
	Data			DATE			NOT NULL,
	FK_Cliente		INT				NOT NULL,
	FK_Balcao		INT				NOT NULL,
	FK_Veiculo		VARCHAR(6)		NOT NULL,
	PRIMARY KEY(Numero),
	FOREIGN KEY (FK_Cliente) REFERENCES RENTACAR.CLIENTE(NIF),
	FOREIGN KEY (FK_Balcao) REFERENCES RENTACAR.BALCAO(Num),
	FOREIGN KEY (FK_Veiculo) REFERENCES RENTACAR.VEICULO(Matricula));

CREATE TABLE RENTACAR.SIMILARIDADE(
	Codigo1		INT		NOT NULL,
	Codigo2		INT		NOT NULL,
	PRIMARY KEY(Codigo1, Codigo2),
	FOREIGN KEY (Codigo1) REFERENCES RENTACAR.TPVEICULO(Codigo),
	FOREIGN KEY (Codigo2) REFERENCES RENTACAR.TPVEICULO(Codigo));