/*CREATE SCHEMA AIRLINE;

CREATE TABLE AIRLINE.AIRPORT(
	AIRPORTCODE		INT				NOT NULL,
	CITY			VARCHAR(30),
	ESTADO			VARCHAR(30),
	NAME			VARCHAR(30)		NOT NULL,
	PRIMARY KEY (AIRPORTCODE));


CREATE TABLE AIRLINE.AIRPLANETYPE (
	TYPENAME	VARCHAR(30)		NOT NULL,
	MAXSEATS	INT				NOT NULL,
	COMPANY		VARCHAR(30)		NOT NULL,
	PRIMARY KEY (TYPENAME));




CREATE TABLE AIRLINE.CANLAND ( 
	AAIRPORTCODE	INT				NOT NULL,
	ATTYPENAME		VARCHAR(30)		NOT NULL,
	PRIMARY KEY ( AAIRPORTCODE, ATTYPENAME),
	FOREIGN KEY (AAIRPORTCODE)REFERENCES AIRLINE.AIRPORT(AIRPORTCODE),
	FOREIGN KEY (ATTYPENAME) REFERENCES AIRLINE.AIRPLANETYPE(TYPENAME));


CREATE TABLE AIRLINE.AIRPLANE ( 
	AIRPLANEID				INT					NOT NULL,
	TOTAL_NO_OF_SEATS		INT					NOT NULL,
	FK_TYPE					VARCHAR(30)			NOT NULL,
	PRIMARY KEY (AIRPLANEID),
	FOREIGN KEY (FK_TYPE) REFERENCES AIRLINE.AIRPLANETYPE(TYPENAME));



CREATE TABLE AIRLINE.FLIGHT (
	NUMBER		INT				NOT NULL,
	AIRLINE		VARCHAR(30)		NOT NULL,
	WEEKDAYS	VARCHAR(30),
	PRIMARY KEY (NUMBER));


CREATE TABLE AIRLINE.FARE (
	CODE			INT			NOT NULL,
	AMOUNT			INT			NOT NULL,
	RESTRICTIONS	VARCHAR(30),
	FLIGHT			INT			NOT NULL,
	PRIMARY KEY (CODE),
	FOREIGN KEY (FLIGHT) REFERENCES AIRLINE.FLIGHT(NUMBER));  


CREATE TABLE AIRLINE.FLIGHTLEG (
	LEG_NO			INT				NOT NULL,
	AASCH_ARR_TIME	DATE			NOT NULL,
	DASCH_DEP_TIME	DATE			NOT NULL,
	FLIGHT			INT				NOT NULL,
	FK_FLDEPAIR		INT				NOT NULL,
	FK_FLARRAIR		INT				NOT NULL,
	PRIMARY KEY (LEG_NO,FLIGHT),
	FOREIGN KEY (FLIGHT) REFERENCES AIRLINE.FLIGHT(NUMBER),
	FOREIGN KEY (FK_FLDEPAIR) REFERENCES AIRLINE.AIRPORT(AIRPORTCODE),
	FOREIGN KEY (FK_FLARRAIR) REFERENCES AIRLINE.AIRPORT(AIRPORTCODE));




CREATE TABLE AIRLINE.LEGINSTANCE (
	DATA					DATE		NOT NULL,
	NO_OF_AVAIL_SEATS		INT			NOT NULL,
	AIRPLANE				INT			NOT NULL,
	FLIGHT_LEG				INT			NOT NULL,
	DDEPTIME				DATE		,
	AARRTIME				DATE		,
	FK_LIARRAIR				INT			NOT NULL,
	FK_LIDEPAIR				INT			NOT NULL,
	FLIGHT_LEG_NO			INT			NOT NULL,
	PRIMARY KEY(DATA,AIRPLANE,FLIGHT_LEG,FLIGHT_LEG_NO),
	FOREIGN KEY (FK_LIARRAIR) REFERENCES AIRLINE.AIRPORT(AIRPORTCODE),
	FOREIGN KEY (FK_LIDEPAIR) REFERENCES AIRLINE.AIRPORT(AIRPORTCODE),
	FOREIGN KEY (AIRPLANE) REFERENCES AIRLINE.AIRPLANE(AIRPLANEID),
	FOREIGN KEY (FLIGHT_LEG, FLIGHT_LEG_NO) REFERENCES AIRLINE.FLIGHTLEG(FLIGHT,LEG_NO));
	
*/

CREATE TABLE AIRLINE.SEAT(
	SEAT_NO		INT			NOT NULL,
	RCUST_NAME	VARCHAR(30)	,
	RCPHONE		INT			,
	LEG_INSTANCE	DATE	NOT NULL,
	PRIMARY KEY(SEAT_NO, LEG_INSTANCE),
	FOREIGN KEY(LEG_INSTANCE) REFERENCES AIRLINE.LEGINSTANCE(DATA));



