/*CREATE SCHEMA CONFERENCIA;*/
/*
CREATE TABLE CONFERENCIA.ARTIGO(
	NRegisto		INT				NOT NULL,
	Titulo			VARCHAR(30),
	PRIMARY KEY(NRegisto));


CREATE TABLE CONFERENCIA.INSTITUICAO(
	Nome		VARCHAR(30)	NOT NULL,
	Endereco	VARCHAR(30),
	PRIMARY KEY(Nome));



CREATE TABLE CONFERENCIA.AUTOR(
	Email		VARCHAR(30)		NOT NULL,
	Nome		VARCHAR(30),
	FK_Inst		VARCHAR(30)		NOT NULL,
	PRIMARY KEY(Email),
	FOREIGN KEY(FK_Inst) REFERENCES CONFERENCIA.INSTITUICAO(Nome));
		
CREATE TABLE CONFERENCIA.ESCRITO(
	ArtNRegisto		INT			NOT NULL,
	AutorEmail		VARCHAR(30)	NOT NULL,
	PRIMARY KEY(ArtNRegisto, AutorEmail),
	FOREIGN KEY(ArtNRegisto) REFERENCES CONFERENCIA.ARTIGO(NRegisto),
	FOREIGN KEY(AutorEmail)	REFERENCES CONFERENCIA.AUTOR(Email));
		
CREATE TABLE CONFERENCIA.PARTICIPANTES(
	Email		VARCHAR(30)	NOT NULL,
	Nome		VARCHAR(30),
	Morada		VARCHAR(30),
	DataInsc	DATE,
	FK_Inst		VARCHAR(30)	NOT NULL,
	PRIMARY KEY(Email),
	FOREIGN KEY(FK_Inst) REFERENCES CONFERENCIA.INSTITUICAO(Nome));
		
CREATE TABLE CONFERENCIA.ESTUDANTE(
	Email			VARCHAR(30)	NOT NULL,
	LocalEletronica	INT,
	PRIMARY KEY(Email),
	FOREIGN KEY(Email) REFERENCES CONFERENCIA.PARTICIPANTES(Email));

	*/
CREATE TABLE CONFERENCIA.NAOESTUDANTE(
	Email			VARCHAR(30)	NOT NULL,
	Ref				INT,
	PRIMARY KEY(Email),
	FOREIGN KEY(Email) REFERENCES CONFERENCIA.PARTICIPANTES(Email));