/*CREATE SCHEMA STOCKS;*/
/*
CREATE TABLE STOCKS.PRODUTO(
	Codigo		INT				NOT NULL,
	Nome		VARCHAR(30),
	Preco		INT				NOT NULL,
	IVA			INT				NOT NULL,
	STOCK		INT				NOT NULL,
	PRIMARY KEY(Codigo));
	

CREATE TABLE STOCKS.FORNECEDOR(
	NIF			INT				NOT NULL,
	Nome		VARCHAR(30),
	Endereco	VARCHAR(30),
	NFax		INT,
	PRIMARY KEY(NIF));

	

CREATE TABLE STOCKS.ENCOMENDA(
	Nencomenda		INT		NOT NULL,
	Data			DATE	NOT NULL,
	FK_Fornecedor	INT		NOT NULL,
	PRIMARY KEY(Nencomenda),
	FOREIGN KEY(FK_Fornecedor) REFERENCES STOCKS.FORNECEDOR(NIF));

	

CREATE TABLE STOCKS.ITEM(
	PCodigo		INT		NOT NULL,
	ENEncomenda	INT		NOT NULL,
	Quantidade	INT		NOT NULL,
	PRIMARY KEY(PCodigo, ENEncomenda),
	FOREIGN KEY(PCodigo) REFERENCES STOCKS.PRODUTO(Codigo),
	FOREIGN KEY(ENEncomenda) REFERENCES STOCKS.ENCOMENDA(Nencomenda));



CREATE TABLE STOCKS.CATEGORIAPRODUTO(
	Codigo		INT				NOT NULL,
	Designacao	VARCHAR(30),
	PRIMARY KEY(Codigo));

CREATE TABLE STOCKS.CONDPAGAMENTO(
	Codigo		INT				NOT NULL,
	Condicao	VARCHAR(30),
	PRIMARY KEY(Codigo));

	

CREATE TABLE STOCKS.TIPOFORNECEDOR(
	CatProdCodigo	INT		NOT NULL,
	FNIF			INT		NOT NULL,
	PRIMARY KEY(FNIF, CatProdCodigo),
	FOREIGN KEY(CatProdCodigo) REFERENCES STOCKS.CATEGORIAPRODUTO(Codigo),
	FOREIGN KEY(FNIF) REFERENCES STOCKS.FORNECEDOR(NIF));
	*/


CREATE TABLE STOCKS.TIPOPAG(
	CondPagCodigo	INT		NOT NULL,
	FNIF			INT		NOT NULL,
	PRIMARY KEY(FNIF, CondPagCodigo),
	FOREIGN KEY(CondPagCodigo) REFERENCES STOCKS.CONDPAGAMENTO(Codigo),
	FOREIGN KEY(FNIF) REFERENCES STOCKS.FORNECEDOR(NIF));